// NileGov Reporting Snapshot Summary — Report Client Script
// Prototype M&E only. NOT official government statistics.
frappe.query_reports["NileGov Reporting Snapshot Summary"] = {
    "filters": [
        {
            "fieldname": "reporting_period_start",
            "label": __("Period Start"),
            "fieldtype": "Date"
        },
        {
            "fieldname": "reporting_period_end",
            "label": __("Period End"),
            "fieldtype": "Date"
        },
        {
            "fieldname": "generated_by",
            "label": __("Generated By"),
            "fieldtype": "Data"
        }
    ],
    "onload": function(report) {
        frappe.msgprint({
            title: __("Prototype Reporting Disclaimer"),
            indicator: "red",
            message: __("<b>PROTOTYPE DATA ONLY.</b><br><br>" +
                        "All metrics in this report are calculated from fictional seed data " +
                        "and are NOT official government statistics.<br><br>" +
                        "This report does not represent live NileGov, NIRA, URA or any " +
                        "Ministry performance data.")
        });
    }
};
