# NileGov Infrastructure Integrations (Mocks & Mappings)
# Digi-Verse Uganda Limited

from nilegov_stack.infrastructure.integrations.simulated_identity_gateway import SimulatedIdentityVerificationGateway
from nilegov_stack.infrastructure.integrations.simulated_payment_gateway import SimulatedPaymentVerificationGateway
