# Notification Entity and State Constants for NileGov Stack
# Digi-Verse Uganda Limited
# Prototype simulation only. No live Government registry access.

from typing import Optional


class RecipientType:
    CITIZEN = "Citizen"
    OFFICER = "Officer"
    SUPERVISOR = "Supervisor"
    DEPARTMENT_QUEUE = "Department Queue"
    SYSTEM = "System"


class NotificationChannel:
    EMAIL = "Email"
    SMS = "SMS"
    WHATSAPP = "WhatsApp"
    PORTAL = "Portal"
    INTERNAL_DESK = "Internal Desk"
    OTHER = "Other"


class NotificationDeliveryStatus:
    DRAFT = "Draft"
    QUEUED = "Queued"
    SIMULATED_SENT = "Simulated Sent"
    SIMULATED_FAILED = "Simulated Failed"
    CANCELLED = "Cancelled"
    NOT_REQUIRED = "Not Required"


class NotificationMessageType:
    RECEIVED = "Request Received"
    REVIEW = "Under Review"
    INFO_REQUIRED = "Information Required"
    PAY_PENDING = "Payment Pending"
    PAY_VERIFIED = "Payment Verified"
    APPROVED = "Approved"
    READY = "Ready for Collection"
    CLOSED = "Closed"
    REJECTED = "Rejected"
    RISK = "SLA At Risk"
    OVERDUE = "SLA Overdue"
    ESCALATED = "Escalated"
    RETURNED = "Returned to Officer"


class NotificationEvent:
    """Represents a simulated communication event generated by the workflow."""

    def __init__(
        self,
        notification_event_id: str,
        service_request_id: str,
        recipient: str,
        channel: str,
        message: str,
        delivery_status: str = NotificationDeliveryStatus.DRAFT,
        citizen_profile_id: Optional[str] = None,
        consent_record_id: Optional[str] = None,
        recipient_type: str = RecipientType.CITIZEN,
        recipient_reference: Optional[str] = None,
        recipient_placeholder: Optional[str] = None,
        message_type: str = NotificationMessageType.RECEIVED,
        notification_type: str = "Status Update",
        message_title: Optional[str] = None,
        message_body_preview: Optional[str] = None,
        consent_checked: bool = False,
        consent_status_at_trigger: Optional[str] = None,
        triggered_by_event: Optional[str] = None,
        scheduled_at: Optional[float] = None,
        simulated_sent_at: Optional[float] = None,
        simulated_failed_at: Optional[float] = None,
        failure_reason: Optional[str] = None,
        disclaimer: str = "Prototype simulation only. No live email, SMS, WhatsApp or portal notification was sent.",
        created_at: Optional[float] = None,
        updated_at: Optional[float] = None
    ):
        self.notification_event_id = notification_event_id
        self.service_request_id = service_request_id
        self.recipient = recipient
        self.channel = channel
        self.message = message
        self.delivery_status = delivery_status
        self.citizen_profile_id = citizen_profile_id
        self.consent_record_id = consent_record_id
        self.recipient_type = recipient_type
        self.recipient_reference = recipient_reference
        self.recipient_placeholder = recipient_placeholder
        self.message_type = message_type
        self.notification_type = notification_type
        self.message_title = message_title
        self.message_body_preview = message_body_preview or message
        self.consent_checked = consent_checked
        self.consent_status_at_trigger = consent_status_at_trigger
        self.triggered_by_event = triggered_by_event
        self.scheduled_at = scheduled_at
        self.simulated_sent_at = simulated_sent_at
        self.simulated_failed_at = simulated_failed_at
        self.failure_reason = failure_reason
        self.disclaimer = disclaimer
        self.created_at = created_at
        self.updated_at = updated_at

        # Basic validations
        self.validate()

    def validate(self):
        if not self.service_request_id:
            raise ValueError("Service Request ID is required.")
        if not self.recipient:
            raise ValueError("Recipient reference is required.")
        if not self.message:
            raise ValueError("Message content is required.")
        
        valid_recipient_types = (
            RecipientType.CITIZEN, RecipientType.OFFICER, RecipientType.SUPERVISOR,
            RecipientType.DEPARTMENT_QUEUE, RecipientType.SYSTEM
        )
        if self.recipient_type not in valid_recipient_types:
            raise ValueError(f"Invalid recipient type: {self.recipient_type}")

        valid_channels = (
            NotificationChannel.EMAIL, NotificationChannel.SMS, NotificationChannel.WHATSAPP,
            NotificationChannel.PORTAL, NotificationChannel.INTERNAL_DESK, NotificationChannel.OTHER
        )
        if self.channel not in valid_channels:
            raise ValueError(f"Invalid channel: {self.channel}")

        valid_statuses = (
            NotificationDeliveryStatus.DRAFT, NotificationDeliveryStatus.QUEUED,
            NotificationDeliveryStatus.SIMULATED_SENT, NotificationDeliveryStatus.SIMULATED_FAILED,
            NotificationDeliveryStatus.CANCELLED, NotificationDeliveryStatus.NOT_REQUIRED
        )
        if self.delivery_status not in valid_statuses:
            raise ValueError(f"Invalid delivery status: {self.delivery_status}")

        valid_message_types = (
            NotificationMessageType.RECEIVED, NotificationMessageType.REVIEW,
            NotificationMessageType.INFO_REQUIRED, NotificationMessageType.PAY_PENDING,
            NotificationMessageType.PAY_VERIFIED, NotificationMessageType.APPROVED,
            NotificationMessageType.READY, NotificationMessageType.CLOSED,
            NotificationMessageType.REJECTED, NotificationMessageType.RISK,
            NotificationMessageType.OVERDUE, NotificationMessageType.ESCALATED,
            NotificationMessageType.RETURNED
        )
        if self.message_type not in valid_message_types:
            raise ValueError(f"Invalid message type: {self.message_type}")

        # Enforce disclaimer
        required_msg = "Prototype simulation only. No live email, SMS, WhatsApp or portal notification was sent."
        if not self.disclaimer or required_msg not in self.disclaimer:
            self.disclaimer = required_msg

    def queue(self):
        """Marks the event as Queued for simulation."""
        if self.delivery_status in (NotificationDeliveryStatus.SIMULATED_SENT, NotificationDeliveryStatus.SIMULATED_FAILED):
            raise ValueError("Cannot queue a completed notification.")
        self.delivery_status = NotificationDeliveryStatus.QUEUED

    def simulated_send(self, sent_at: float):
        """Marks the event as Simulated Sent."""
        self.delivery_status = NotificationDeliveryStatus.SIMULATED_SENT
        self.simulated_sent_at = sent_at

    def simulated_fail(self, failed_at: float, reason: str):
        """Marks the event as Simulated Failed with a reason."""
        self.delivery_status = NotificationDeliveryStatus.SIMULATED_FAILED
        self.simulated_failed_at = failed_at
        self.failure_reason = reason

    def cancel(self):
        """Cancels a draft or queued notification."""
        if self.delivery_status in (NotificationDeliveryStatus.SIMULATED_SENT, NotificationDeliveryStatus.SIMULATED_FAILED):
            raise ValueError("Cannot cancel a completed notification.")
        self.delivery_status = NotificationDeliveryStatus.CANCELLED
