# NileGov Infrastructure Repositories
# Digi-Verse Uganda Limited

from nilegov_stack.infrastructure.repositories.service_request_repository import InMemoryServiceRequestRepository
from nilegov_stack.infrastructure.repositories.frappe_service_request_repository import FrappeServiceRequestRepository

from nilegov_stack.infrastructure.repositories.citizen_profile_repository import InMemoryCitizenProfileRepository
from nilegov_stack.infrastructure.repositories.frappe_citizen_profile_repository import FrappeCitizenProfileRepository

from nilegov_stack.infrastructure.repositories.consent_record_repository import InMemoryConsentRecordRepository
from nilegov_stack.infrastructure.repositories.frappe_consent_record_repository import FrappeConsentRecordRepository

from nilegov_stack.infrastructure.repositories.evidence_document_repository import InMemoryEvidenceDocumentRepository
from nilegov_stack.infrastructure.repositories.frappe_evidence_document_repository import FrappeEvidenceDocumentRepository

from nilegov_stack.infrastructure.repositories.sla_rule_repository import InMemorySLARuleRepository
from nilegov_stack.infrastructure.repositories.frappe_sla_rule_repository import FrappeSLARuleRepository

from nilegov_stack.infrastructure.repositories.notification_event_repository import InMemoryNotificationEventRepository
from nilegov_stack.infrastructure.repositories.frappe_notification_event_repository import FrappeNotificationEventRepository

from nilegov_stack.infrastructure.repositories.payment_record_repository import InMemoryPaymentRecordRepository
from nilegov_stack.infrastructure.repositories.frappe_payment_record_repository import FrappePaymentRecordRepository



