# Quality Gate: Forbidden String Scan
# Digi-Verse Uganda Limited

import os
import re
import pytest

FORBIDDEN_PATTERNS = [
    (r"generated by chatgpt", "AI assistant residue"),
    (r"generated by claude", "AI assistant residue"),
    (r"generated by gemini", "AI assistant residue"),
    (r"ai-generated", "AI assistant residue"),
    (r"live nira access", "Unauthorized registry claims"),
    (r"live ura access", "Unauthorized registry claims"),
    (r"live ughub integration", "Unauthorized registry claims"),
    (r"fully compliant", "Premature compliance statement"),
    (r"blockchain", "Unsupported technology buzzword"),
    (r"decentralized ledger", "Unsupported blockchain terminology"),
    (r"machine learning", "Unsupported technology buzzword"),
    (r"artificial intelligence", "Unsupported technology buzzword"),
    (r"lorem ipsum", "Placeholder residue"),
    (r"coming soon", "Placeholder residue")
]


def should_scan_file(file_path: str) -> bool:
    """Filters out build directories, virtual environments, caches, and backups."""
    ignored_patterns = [
        r"\.git/",
        r"\.pytest_cache/",
        r"__pycache__/",
        r"venv/",
        r"env/",
        r"node_modules/",
        r"dist/",
        r"build/",
        r"\.egg-info/",
        r"\.tar\.gz$",
        r"\.gpg$"
    ]
    
    normalized_path = file_path.replace(os.sep, "/")
    if "test_no_forbidden_public_strings.py" in normalized_path:
        return False
        
    for pattern in ignored_patterns:
        if re.search(pattern, normalized_path, re.IGNORECASE):
            return False
            
    # Scan only source code, configs, shell scripts, and documentation files
    valid_extensions = {".py", ".md", ".yml", ".yaml", ".json", ".conf", ".sh", ".cnf", ".txt", ".ini"}
    _, ext = os.path.splitext(file_path)
    return ext in valid_extensions


def get_scan_files():
    """Finds all files in the repository to scan for forbidden strings."""
    current_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))))
    scan_files = []
    for root, _, files in os.walk(current_dir):
        for file in files:
            full_path = os.path.join(root, file)
            if should_scan_file(full_path):
                scan_files.append(full_path)
    return scan_files


@pytest.mark.parametrize("file_path", get_scan_files())
def test_no_forbidden_strings_in_public_files(file_path):
    """Enforces proper branding, legal disclaimers, and scans for AI residues."""
    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        content = f.read()
        
    for pattern, description in FORBIDDEN_PATTERNS:
        match = re.search(pattern, content, re.IGNORECASE)
        assert not match, (
            f"Forbidden string matching '{pattern}' ({description}) detected in file {file_path}. "
            f"Remove this string before submitting code."
        )
